test=['http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=1;template=results;type=batting',
      'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=2;template=results;type=batting',
      'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=3;template=results;type=batting',
      'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=4;template=results;type=batting',
      'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=5;template=results;type=batting',
      'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=6;template=results;type=batting',
      'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=7;template=results;type=batting',
      'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=8;template=results;type=batting']
teams=['England','Australia','SouthAfrica','Westindies','Newzealand','INDIA','Pakistan','Srilanka']
odi=['http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=1;template=results;type=batting',
     'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=2;template=results;type=batting',
     'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=3;template=results;type=batting',
     'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=4;template=results;type=batting',
     'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=5;template=results;type=batting',
     'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=6;template=results;type=batting',
     'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=7;template=results;type=batting',
     'http://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;spanmax1=27+Jul+2018;spanmin1=27+Jul+2016;spanval1=span;team=8;template=results;type=batting',]